// Map JSX/React event names to their standard DOM counterpart.
const eventsMap = {
  onAbort: "abort",
  onAnimationCancel: "animationcancel",
  onAnimationEnd: "animationend",
  onAnimationIteration: "animationiteration",
  onAnimationStart: "animationstart",
  onAuxClick: "auxclick",
  onBeforeInput: "beforeinput",
  onBlur: "blur",
  onChange: "change",
  onCompositionEnd: "compositionend",
  onCompositionStart: "compositionstart",
  onCompositionUpdate: "compositionupdate",
  onClick: "click",
  onClose: "close",
  onContextMenu: "contextmenu",
  onDoubleClick: "dblclick",
  onError: "error",
  onFocus: "focus",
  onGotPointerCapture: "gotpointercapture",
  onInput: "input",
  onInvalid: "invalid",
  onKeyDown: "keydown",
  onKeyPress: "keypress",
  onKeyUp: "keyup",
  onLoad: "load",
  onLoadEnd: "loadend",
  onLoadStart: "loadstart",
  onLostPointerCapture: "lostpointercapture",
  onMouseDown: "mousedown",
  onMouseMove: "mousemove",
  onMouseOut: "mouseout",
  onMouseOver: "mouseover",
  onMouseUp: "mouseup",
  onPointerCancel: "pointercancel",
  onPointerDown: "pointerdown",
  onPointerEnter: "pointerenter",
  onPointerLeave: "pointerleave",
  onPointerMove: "pointermove",
  onPointerOut: "pointerout",
  onPointerOver: "pointerover",
  onPointerUp: "pointerup",
  onReset: "reset",
  onResize: "resize",
  onScroll: "scroll",
  onSelect: "select",
  onSelectionChange: "selectionchange",
  onSelectStart: "selectstart",
  onSubmit: "submit",
  onTouchCancel: "touchcancel",
  onTouchEnd: "touchend",
  onTouchMove: "touchmove",
  onTouchStart: "touchstart",
  onTransitionCancel: "transitioncancel",
  onTransitionEnd: "transitionend",
  onTransitionStart: "transitionstart",
  onToggle: "toggle",
  onWheel: "wheel",
  onDrag: "drag",
  onDragEnd: "dragend",
  onDragEnter: "dragenter",
  onDragExit: "dragexit",
  onDragLeave: "dragleave",
  onDragOver: "dragover",
  onDragStart: "dragstart",
  onDrop: "drop",
  onFocusOut: "focusout",
};

export function getNativeEventName(reactEventName: string): string | undefined {
  return eventsMap[reactEventName as keyof typeof eventsMap];
}
