# Copyright (c) 2026 hangtiancheng
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Deploy to hangtiancheng.github.io github pages # 工作流名

on: # 触发工作流的 github 事件, 例如 push, pull_request 等
  push: # push 操作时, 触发工作流
    # tags: # 指定 tag 上的 push 操作, 才会触发工作流
    #   - "v*.*.*" # 指定 tag
    branches:
      - gh-pages
# 例如 git tag v0.0.1 && git push origin v0.0.1 时, 才会触发工作流

jobs: # 工作流中的作业
  build-and-deploy: # 作业名
    runs-on: ubuntu-latest # 操作系统

    steps: # 作业的步骤
      - name: checkout # 步骤名
        uses: actions/checkout@v4 # 使用预定义的 actions/checkout 动作 checkout 仓库

      - name: setup Node.js
        uses: actions/setup-node@v4 # 使用预定义的 actions/setup-node 动作安装 Node.js
        with: # 动作的参数
          node-version: 24 # 指定 Node.js 版本

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4 # 使用预定义的 peaceiris/actions-gh-pages 动作部署 GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: "hangtiancheng"
          user_email: "161043261@qq.com"
